import {
  pgTable,
  uuid,
  text,
  boolean,
  jsonb,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { users } from "./users";

// ============================================================
// weekly_digests
// ============================================================
// Pre-computed weekly summary of platform highlights.
// Generated by a background job (or on-demand) once per week.

export const weeklyDigests = pgTable(
  "weekly_digests",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),

    weekStart: timestamp("week_start", { withTimezone: true }).notNull(),
    weekEnd: timestamp("week_end", { withTimezone: true }).notNull(),

    // Array of { id, title, slug, voteCount }
    topEntries: jsonb("top_entries")
      .notNull()
      .default(sql`'[]'::jsonb`),

    // Array of { id, name, slug, downloads }
    topSkills: jsonb("top_skills")
      .notNull()
      .default(sql`'[]'::jsonb`),

    // Array of { id, username, displayName, avatarUrl, reputation }
    topContributors: jsonb("top_contributors")
      .notNull()
      .default(sql`'[]'::jsonb`),

    // { newEntries, newSkills, newUsers, totalVotes, totalComments }
    stats: jsonb("stats")
      .notNull()
      .default(sql`'{}'::jsonb`),

    generatedAt: timestamp("generated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    index("weekly_digests_week_idx").on(t.weekStart),
  ],
);

// ============================================================
// user_digest_preferences
// ============================================================
// Per-user settings for digest delivery.

export const userDigestPreferences = pgTable(
  "user_digest_preferences",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    emailDigest: boolean("email_digest").notNull().default(true),

    // 'weekly' | 'biweekly' | 'monthly'
    digestFrequency: text("digest_frequency").notNull().default("weekly"),

    // Array of source identifiers the user wants to follow
    preferredSources: jsonb("preferred_sources")
      .notNull()
      .default(sql`'[]'::jsonb`),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),

    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    uniqueIndex("user_digest_prefs_user_uk").on(t.userId),
  ],
);

// --- Type exports ---

export type DigestTopEntry = {
  id: string;
  title: string;
  slug: string;
  voteCount: number;
};

export type DigestTopSkill = {
  id: string;
  name: string;
  slug: string;
  downloads: number;
};

export type DigestTopContributor = {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  reputation: number;
};

export type DigestStats = {
  newEntries: number;
  newSkills: number;
  newUsers: number;
  totalVotes: number;
  totalComments: number;
};

export type WeeklyDigest = typeof weeklyDigests.$inferSelect;
export type NewWeeklyDigest = typeof weeklyDigests.$inferInsert;
export type UserDigestPreference = typeof userDigestPreferences.$inferSelect;
export type NewUserDigestPreference = typeof userDigestPreferences.$inferInsert;
